// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCI8apJe78QCAzZFIlRGG96wG3BP0NPHDM',
    appId: '1:740529960631:android:fe45d25689681cdd873f32',
    messagingSenderId: '740529960631',
    projectId: 'ai-cockpit-app',
    storageBucket: 'ai-cockpit-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBk1gfkSxigUTyiJzFmnnFznRWoa2yG9cE',
    appId: '1:740529960631:ios:1a5558d28b42fe9f873f32',
    messagingSenderId: '740529960631',
    projectId: 'ai-cockpit-app',
    storageBucket: 'ai-cockpit-app.firebasestorage.app',
    androidClientId: '740529960631-k3250etdpru73vgm4if78dluhg3q23iq.apps.googleusercontent.com',
    iosClientId: '740529960631-o6thcchktdehc0qpcdp8ppfbboujckpf.apps.googleusercontent.com',
    iosBundleId: 'com.bacoding.aicockpitapp',
  );

}